version: 2
jobs:
  lint_git_commits:
    docker:
      - image: python:3.7
    working_directory: ~/typed_json_dataclass
    steps:
      - checkout
      - run: pip install gitlint==0.10.0
      - run: gitlint

  lint:
    docker:
      - image: python:3.7
    working_directory: ~/typed_json_dataclass
    steps:
      - checkout
      - run: pip install pipenv==2018.11.26
      - run: pipenv install --dev
      - run: make lint

  test:
    docker:
      - image: python:3.7
    working_directory: ~/typed_json_dataclass
    steps:
      - checkout
      - run: pip install pipenv==2018.11.26
      - run: pipenv install --dev
      - run: make test

      - store_artifacts:
          path: htmlcov

      - store_test_results:
          path: test-results

  upload_coverage:
    docker:
      - image: python:3.7
    working_directory: ~/typed_json_dataclass
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: make test
      - run: pipenv run codecov -t $CODECOV_TOKEN

  # deploy:
  #   docker:
  #     - image: python:3.7
  #   working_directory: ~/typed_json_dataclass
  #   steps:
  #     - checkout
  #     - run: pip install pipenv
  #     - run: pipenv install --dev
  #     - run:
  #         name: Verify git tag vs. version
  #         command: |
  #           echo "CIRCLE_TAG=$(git tag -l --points-at HEAD)" > .env
  #           cat .env
  #           pipenv run python setup.py verify
  #     - run:
  #         name: Init .pypirc
  #         command: |
  #           echo -e "[pypi]" >> ~/.pypirc
  #           echo -e "username = abatilo" >> ~/.pypirc
  #           echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
  #     - run:
  #         name: Create packages
  #         command: |
  #           pipenv run python setup.py sdist
  #           pipenv run python setup.py bdist_wheel
  #     - run:
  #         name: Upload packages
  #         command: |
  #           pipenv run twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
      - lint_git_commits
      - test
      - upload_coverage:
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - lint_git_commits
      #       - test
      #     filters:
      #       branches:
      #         only: deploy
      #       tags:
      #         only: /[0-9]\.[0-9]\.[0-9]/
